#!/bin/sh

container=$(docker create dyne/decodeos:latest)
container=$(docker start $container)
onion=$(docker exec  $container dam-client -gen 2>&1| awk '/Our hostname/ {print $6}')
echo "New DECODE-OS node address: $onion"
image=$(docker commit $container dyne/decodeos:$onion)
echo "Docker image: dyne/decodeos:$onion"
echo "$image"
container=$(docker stop $container)


