#!/usr/bin/env zsh

blend_name="decode"
blend_vers="0.0"
image_name="${blend_name}-${blend_vers}-${arch}"


golang_version="1.9.2"
golang_arch="amd64"
golang_url="https://storage.googleapis.com/golang/go${golang_version}.linux-${golang_arch}.tar.gz"

tomb_version="v2.4"
tomb_url="https://github.com/dyne/tomb.git"

musl_version="v.1.1.18"
musl_url="git://git.musl-libc.org/musl"

netdata_version="1.7.0"
netdata_url="https://github.com/firehol/netdata/releases/download/v${netdata_version}/netdata-${netdata_version}.tar.gz"

# mongodb source build
#mongodb_version="3.4.6"
#mongodb_url="https://fastdl.mongodb.org/src/mongodb-src-r${mongodb_version}.tar.gz"
# mongodb binary build
mongodb_version="3.4.9"
mongodb_url="https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian81-${mongodb_version}.tgz"

# XXX: multichain currently installed from compiled binaries, needs db4.8 (devuan pkg)
multichain_version="1.0.1"
multichain_url="https://www.multichain.com/download/multichain-${multichain_version}.tar.gz"

size="4098"
#filesystem="xfs"
filesystem="ext4"

#TAR_STAGE4=true

extra_packages+=(

	# application space
	openjdk-8-jre-headless
	libversioneer-clojure

	# base system
	eudev
	zsh
	tmux
	curl
	cryptsetup
	openssh-server
	openssh-client
	gnupg2
	dirmngr
	pcsc-tools
	xorg
	surf2

	python2.7
	python3

	# minimalism
	busybox-static
	busybox-syslogd

	# utilities
	mlocate
	gettext
	miscfiles

	# for xfs
	xfsprogs

	# troubleshooting
	lsof
	htop
	iftop
	iotop
	strace

	# build tools
	build-essential
	cmake
	pkg-config
	zlib1g-dev
	uuid-dev
	autoconf
	automake
	libtool
	gcc-6-plugin-dev
	libncurses5-dev
	flex
	libbison-dev
	libtool-bin
	libtool
	libssl-dev
	libgcrypt20
	libgcrypt20-dev
	equivs

	# mongodb build deps
	#scons
	#libboost-filesystem-dev
	#libboost-program-options-dev
	#libboost-system-dev
	#libboost-thread-dev
)

purge_packages=(
	# temporary fix for ASCII bug on rsyslog
	rsyslog
	# dbus
	# gnome-icon-theme
)

finalize_purge_packages=(
	#autoconf
	#automake
	#flex
	#equivs
)
