#!/usr/bin/env zsh

blend_name="decode"
blend_vers="1.0.0"
image_name="${blend_name}-${blend_vers}-${arch}"
vm_name="${blend_name}-${blend_vers}-${arch}"

dyneci_url="https://sdk.dyne.org:4443/job"


tomb_version="v2.4"
tomb_url="https://github.com/dyne/tomb.git"

musl_version="v.1.1.19"
musl_url="git://git.musl-libc.org/musl"

netdata_version="1.9.0"
netdata_url="https://github.com/firehol/netdata/releases/download/v${netdata_version}/netdata-${netdata_version}.tar.gz"

stem_version="1.6.0"
stem_url="https://git.torproject.org/stem.git"

tordam_url="github.com/decodeproject/tor-dam/..."

zenroom_url="${dyneci_url}/zenroom-static-${arch}/lastSuccessfulBuild/artifact/src/zenroom-static"

golang_url="${dyneci_url}/go-binaries/lastBuild/architecture=${arch}/artifact/go.${arch}.tar.gz"

chainspace_url="https://github.com/chainspace/chainspace"
chainspacedist_url="${dyneci_url}/chainspace-jar/lastSuccessfulBuild/artifact/chainspacedist.tgz"


size="4098"
filesystem="btrfs"

TAR_STAGE4=true

extra_packages+=(
	openrc
	eudev
	zsh
	tmux
	curl
	cryptsetup
	openssh-server
	psmisc
	btrfs-progs
	openssh-client
	gnupg2
	dirmngr
	pcsc-tools
	tor
	redis-tools
	redis-server
	paxctl
	net-tools

	default-jre-headless

	apt-transport-tor
	apt-transport-https
	deb.torproject.org-keyring

	python2.7
	python3

	# minimalism
	busybox-static

	# utilities
	mlocate
	gettext
	miscfiles
	tree

	# troubleshooting
	lsof
	htop
	iftop
	iotop
	strace

	python-pip
	python3-pip
	libpython-dev
	libffi-dev
	python-tox
	python-cffi
	python-pytest
	python-pytest-cov
	python-msgpack
	python-numpy
	python3-numpy
	python-requests
	python3-requests
	sqlite
	sqlite3
	libssl1.0-dev


	# build tools
	build-essential
	cmake
	pkg-config
	zlib1g-dev
	uuid-dev
	autoconf
	automake
	libtool
	gcc-6-plugin-dev
	libncurses5-dev
	flex
	libbison-dev
	libtool-bin
	libtool
	libgcrypt20
	libgcrypt20-dev
	equivs
)

purge_packages=(
	dbus
	elogind
	gnome-icon-theme
	sysv-rc
)

finalize_purge_packages=(
	#autoconf
	#automake
	#flex
	#equivs
)
